services:
#    cms_blog.example:
#        class: CMS\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    app.form.type.task:
        class: CMS\BlogBundle\Form\ArticleType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }