version: "3"
services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "symfony"
            POSTGRES_USER: "symfony"
            POSTGRES_DB: "symfony"

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        links:
            - db:postgres
        volumes:
            - ./app:/app

    httpd:
        image: httpd:latest
        ports:
            - "80:80"
        volumes:
            - ./app:/app
            - ./httpd/conf:/usr/local/apache2/conf
            - ./logs:/logs
        links:
            - php
    node:
        image: node:latest
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./frontApp:/home/node/app
        expose:
            - "8081"
        #command: "npm start"