category_index:
    path:     /
    defaults: { _controller: "CMSBlogBundle:Category:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBlogBundle:Category:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "CMSBlogBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBlogBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBlogBundle:Category:delete" }
    methods:  DELETE
