cms_blog:
    resource: "@CMSBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
user_registration:
    path:     /register
    defaults: { _controller: CMSBlogBundle:Registration:register }

user_profile:
    path:     /profile
    defaults: { _controller: CMSBlogBundle:Profile:show }

login_route:
    path:  /login
    defaults: { _controller: CMSBlogBundle:Security:login }

login_check:
    path: /admin/login_check

login_route_admin:
    path:  /admin/login
    defaults: { _controller: CMSBlogBundle:Security:login }

#login_check_admin:
#    path: /admin/login_check
    # no controller is bound to this route
    # as it's handled by the Security system