cms_blog:
    resource: "@CMSBlogBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
user_registration:
    path:     /register
    defaults: { _controller: CMSBlogBundle:Registration:register }

user_profile:
    path:     /profile
    defaults: { _controller: CMSBlogBundle:Profile:show }

login_route:
    path:  /login
    defaults: { _controller: CMSBlogBundle:Security:login }

login_check:
    path: /admin/login_check

login_route_admin:
    path:  /admin/login
    defaults: { _controller: CMSBlogBundle:Security:login }

auth-tokens:
    type:     rest
    resource: CMS\BlogBundle\Controller\AuthTokenController

articles:
    type:    rest
    resource: CMS\BlogBundle\Controller\ArticleRestController

images:
    type:    rest
    resource: CMS\BlogBundle\Controller\ImageRestController
