# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        CMS\BlogBundle\Entity\User:
           algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory:
        #    memory: ~
        cms_db_user:
            entity:
                class: CMSBlogBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        #main:
            #anonymous: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #pattern:    ^/
            #http_basic: ~
            #provider: cms_db_user
            #form_login:
            #   login_path: /login
            #   check_path: /login_check
            #   default_target_path: /blog

        login_firewall_admin:
            pattern: ^/admin/login$
            anonymous: ~
        admin:
            pattern:    ^/admin
            http_basic: ~
            provider: cms_db_user
            form_login:
               login_path: /admin/login
               check_path: /admin/login_check
               default_target_path: /admin

    access_control:
    - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_SUPER_ADMIN }

    