cms_blog_article:
    resource: "@CMSBlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

cms_blog_home:
    path: /{page}
    defaults: { _controller: CMSBlogBundle:Blog:index , page:0}
    requirements:
        page: \d+

cms_blog_debug:
    path: /debug/{page}
    defaults: { _controller: CMSBlogBundle:Blog:debug , page:0}
    requirements:
        page: \d+

cms_blog_article_debug:
    path: /debug-article/{slug}
    defaults: { _controller: CMSBlogBundle:Blog:debugArticle }

cms_blog_rand:
    path: /random
    defaults: { _controller: "CMSBlogBundle:Blog:random" }

cms_blog_reply:
    resource: "@CMSBlogBundle/Resources/config/routing/reply.yml"
    prefix:   /reply

cms_blog_category:
        resource: "@CMSBlogBundle/Resources/config/routing/category.yml"
        prefix:   /category

cms_blog_image:
        resource: "@CMSBlogBundle/Resources/config/routing/image.yml"
        prefix:   /image

cms_blog_admin:
        resource: "@CMSBlogBundle/Resources/config/routing/admin.yml"
        prefix:   /admin


cms_blog_view:
    path: /article/{slug}
    defaults: { _controller: "CMSBlogBundle:Blog:show" }


cms_blog_search:
    path: /recherche/{query}
    defaults: { _controller: "CMSBlogBundle:Blog:search" }

contact_show:
    path: /about
    defaults: { _controller: "CMSBlogBundle:Blog:about" }

cms_blog_cat:
    path: /category/{category}-{title}/{page}
    defaults: { _controller: CMSBlogBundle:Blog:cat, page:0, title:null }
