<?php

namespace CMS\BlogBundle\Repository;

/**
 * StatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
