reply_index:
    path:     /
    defaults: { _controller: "CMSBlogBundle:Reply:index" }
    methods:  GET

reply_show:
    path:     /{id}/show
    defaults: { _controller: "CMSBlogBundle:Reply:show" }
    methods:  GET

reply_new:
    path:     /new/{id}
    defaults: { _controller: "CMSBlogBundle:Reply:new" }
    methods:  [GET, POST]

reply_edit:
    path:     /{id}/edit
    defaults: { _controller: "CMSBlogBundle:Reply:edit" }
    methods:  [GET, POST]

reply_delete:
    path:     /{id}/delete
    defaults: { _controller: "CMSBlogBundle:Reply:delete" }
    methods:  DELETE
